NewspaperAppProject/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('users/', include('users.urls')),
    path('users/', include('allauth.urls')),
    path('users/', include('django.contrib.auth.urls'))
]

urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('opinions/', views.OpinionPageView.as_view(), name='opinion'),

]

users/urls.py
from django.urls import path
from . import views


urlpatterns = [
        path('signup/', views.SignUp.as_view(), name='signup'),
        path('login/', views.Login.as_view() , name = 'login'),
        path('writer/<int:pk>/', views.WritersPage.as_view() , name = 'writerspage'),
        path('writer/signup/', views.WriterSignUp.as_view(), name = 'writersignup'),
        path('update/<int:pk>', views.UserUpdateForm.as_view(), name = 'usersupdate'),
        path('update/writer/profile/<int:pk>', views.UpdateWriterProfile.as_view(), name = 'writerprofile'),
        path('activate/<uidb64>/<token>', views.activate, name='activate'),
]

users/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import AbstractUser , BaseUserManager
from django.forms import BooleanField, CharField, SlugField
from django.utils.translation import gettext_lazy as _
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils.text import slugify
from django_countries.fields import CountryField



class CustomUser(AbstractUser):
    class Type(models.TextChoices):
        ADMIN = 'ADMIN', 'admin'
        WRITER='WRITER', 'writer'
        READER='READER', 'reader'

    type_choice = Type.READER

    username = models.CharField(max_length=255,blank=True, null=True, unique=False)
    first_name = models.CharField(max_length= 100, blank=True, null=True)
    email = models.CharField(max_length=150, blank=True, unique=True, null=True)
    middle_name = models.CharField(max_length=150 , blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    type = models.CharField(_('Type'), max_length=50, choices=Type.choices)
    slug = models.SlugField(max_length=264, unique=True, null=True)
    



    REQUIRED_FIELDS = ['username', 'first_name', 'last_name', 'password', 'type']
    USERNAME_FIELD = 'email'


    def get_full_name(self):
        if self.middle_name:
            return self.first_name + ' ' + self.middle_name + ' ' + self.last_name 
        else:
            return super().get_full_name()

    def get_name(self):
        return self.first_name + ' ' + self.last_name

    def __str__(self):
        return "{}".format(self.email)

    def save(self, *args, **kwargs):
        if self.id:
            self.type = self.type_choice
        return super().save(*args , **kwargs)

    def is_writer(self):
        return True if self.type.lower() == 'writer' else False 

    def is_reader(self):
        return True if self.type.lower() == 'reader' else False



class AdminManager(BaseUserManager):
    def get_queryset(self, *args, **kwargs):
        results = super().get_queryset(*args, **kwargs)
        return results.filter(type=CustomUser.Type.ADMIN)


class Admin(CustomUser):

    type_choice = CustomUser.Type.ADMIN
    admin = AdminManager()

    class Meta:
        proxy = True

    def save(self ,*args , **kwargs):
        self.type = self.type_choice
        if self.type == 'ADMIN':   
            self.is_staff = True
            return super().save(*args , **kwargs)


class AdminProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    admin_id = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return "{}".format(self.user.email)


@receiver(post_save, sender=Admin)
def create_user_profile(sender, instance, created, **kwargs):
    if created and instance.type == "ADMIN":
        AdminProfile.objects.create(user=instance)


class ReaderManager(BaseUserManager):
    def get_queryset(self, *args, **kwargs):
        results = super().get_queryset(*args, **kwargs)
        return results.filter(type=CustomUser.Type.READER)


class Reader(CustomUser):

    type_choice = CustomUser.Type.READER

    student = ReaderManager()

    class Meta:
        proxy = True

    def welcome(self):
        return "Only for students"

    def save(self, *args, **kwargs):
        self.type = self.type_choice
        return super().save(*args , **kwargs)


@receiver(post_save, sender=Reader)
def create_user_profile(sender, instance, created, **kwargs):
    if created and instance.type == "READER":
        ReaderProfile.objects.create(user=instance)


class ReaderProfile(models.Model):
    user = models.OneToOneField(Reader, on_delete=models.CASCADE)
    reader_id = models.IntegerField(null=True, blank=True) 
    nationality = CountryField(null = True, blank_label = 'select country')

    def __str__(self):
        return "{}".format(self.user.email)



class WriterManager(BaseUserManager):
    def get_queryset(self, *args, **kwargs):
        results = super().get_queryset(*args, **kwargs)
        return results.filter(type=CustomUser.Type.WRITER)


class Writer(CustomUser):

    type_choice = CustomUser.Type.WRITER

    writer = WriterManager()

    class Meta:
        proxy = True

    def welcome(self):
        return "Only for teachers"

    def save(self, *args, **kwargs):
        self.type = self.type_choice
        self.slug = slugify(self.get_name())
        return super().save(*args , **kwargs)

    def get_absolute_url(self):
        return reverse('writerspage', kwargs = {'pk' : str(self.id)})
      


class WriterProfile(models.Model):
    user = models.OneToOneField(Writer, on_delete=models.CASCADE)
    image = models.ImageField(default = '666201.png', blank= False, null = False,  upload_to = 'images/')
    bio = models.TextField(null=True, blank=True)
    education = models.CharField(max_length=255 , null=True, blank=True)
    nationality = CountryField(null = True, blank_label = 'select country')

    def __str__(self):
        return "{}".format(self.user.email)

    def get_absolute_url(self):
        return reverse('writerspage' , kwargs= {'pk': self.user.id})


@receiver(post_save, sender=Writer)
def create_user_profile(sender, instance, created, **kwargs):
    if created and instance.type == "WRITER":
        WriterProfile.objects.create(user=instance)




# Create your models here.

users/forms.py
from dataclasses import field
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core.exceptions import ValidationError  
from django.forms.fields import EmailField  
from django.forms.forms import Form 
from django import forms
from .models import *
import time



class ReaderCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Reader
        fields = ('email', 'first_name' , 'last_name')

class WriterCreationForm(UserCreationForm):  
    class Meta(UserCreationForm.Meta):
        model = Writer
        fields = ('email', 'first_name' ,'middle_name', 'last_name' , 'password1' , 'password2')
  

class AdminCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Admin
        fields = ('email', 'first_name' , 'last_name' , 'type')

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username' , 'email')

class WriterProfileForm(forms.ModelForm):
    class Meta:
        model = WriterProfile
        fields = ('user', 'image' , 'bio' , 'education', 'nationality')

users/views.py
from turtle import update
from django.shortcuts import render, redirect , get_object_or_404
from django.template.loader import render_to_string
from users.models import *
from articles.models import Article
from django.urls import reverse_lazy , reverse
from django.views import generic
from django.contrib import messages
from django.contrib.auth.views import LoginView
from .forms import *
from django.conf import settings
from django.http import Http404,   HttpResponse, HttpResponseForbidden, HttpResponseRedirect
from django.contrib.auth import authenticate , login, get_user_model
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage , send_mail
from .tokens import account_activation_token

#Creating a LoginForm Class

def user_not_authenticated(function=None, redirect_url='/'):
    def decorator(view_func):
        def _wrapped_view(request, *args, **kwargs):
            if request.user.is_authenticated:
                return redirect(redirect_url)
                
            return view_func(request, *args, **kwargs)

        return _wrapped_view

    if function:
        return decorator(function)

    return decorator


def activateEmail(request, user, to_email):
    mail_subject ='Activate your account'
    user = get_object_or_404(CustomUser , email = user)
    token = account_activation_token.make_token(user)
    message = render_to_string('users/template_activate_account.html', {
        'user': user.username,
        'domain': get_current_site(request).domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': token,
        'protocol': 'https' if request.is_secure() else 'http'
    })
    email = EmailMessage(mail_subject,  message,  to=[to_email])
    if email.send():
        messages.success(request, f'Dear <b>{user}</b>, please go to you email <b>{to_email}</b> inbox and click on \
            received activation link to confirm and complete the registration. <b>Note:</b> Check your spam folder.')
    else:
        messages.error(request, f'Problem sending confirmation email to {to_email}, check if you typed it correctly.')

def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        messages.success(request, 'Thank you for your email confirmation. Now you can login your account.')
        return redirect('login')
    else:
        messages.error(request, 'Activation link is invalid!')
    
    return redirect('home')



class SignUp(generic.CreateView):
    form_class = ReaderCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

    
    def get(self, request ,*args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home')
        else:
            print(self.request.user)
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        print(user)
        print("POST REQUEST" , self.request.POST)
        user = user.email
        activateEmail(self.request, user, form.cleaned_data['email'])
        return HttpResponseRedirect(self.success_url)
    

class Login(LoginView):

    def form_valid(self, form):
        email = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(self.request, email = email, password = password)

        if user.is_authenticated:
            customuser = CustomUser.objects.get(email = email)
            if customuser.type.lower() == 'writer':
                login(self.request , user)
                self.success_url = reverse('writerspage', kwargs= {'pk': user.id})
                return HttpResponseRedirect(self.success_url)
            elif customuser.type.lower() == 'reader':
                login(self.request , user)
                self.success_url = reverse('home')
                return HttpResponseRedirect(self.success_url)


#Overriding the login in view can creating a login

class WriterSignUp(generic.CreateView):
    model = Writer
    form_class = WriterCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration\writer-signup.html'

    def form_valid(self, form):
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            activateEmail(self.request, user, form.cleaned_data['email'])
            return HttpResponseRedirect(self.success_url)
        else:
            for error in list(form.errors.values):
                messages.error(self.request, error)

class WritersPage(generic.DetailView):

    model = Writer
    template_name = 'users/writerspage.html'

    #List of articles by the user

    #Using the slug or pk to find a list of articles written by the user.

    def get(self, request, *args, **kwargs):
        super().get(request, *args, **kwargs)
        self.object = Writer.objects.get(id=kwargs.get(self.pk_url_kwarg))
        context = self.get_context_data()
        context['writerbio'] = self.get_writer_bio(self.object)
        articles = Article.objects.filter(author = self.object)
        print(self.request.META.get('HTTP_REFERER'))
        if articles != None:
            context['articles'] = articles
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        super().get_context_data(**kwargs)
        context = {}
        if self.object:
            context['object'] = self.object
        context.update(kwargs)
        return context


    def get_writer_bio(self, user):
        writerprofile = WriterProfile.objects.get(user = user)
        return writerprofile


class UserUpdateForm(generic.UpdateView):

    fields = ['first_name' , 'last_name' , 'middle_name' ]
    template_name = 'users/usersupdate.html'


    def test_func(self , **kwargs):
        if self.request.user.id != kwargs.get('pk'):
            return HttpResponseRedirect('home')


    def get(self, request, *args , **kwargs):
        if self.request.user.is_authenticated:
            self.writersbio = None
            self.test_func(**kwargs)
            if self.request.user.type.lower() == 'writer':
                self.model= Writer
                self.object = Writer.objects.get(id = kwargs.get('pk'))
                self.writersbio = WriterProfile.objects.get(user = self.object) 
            else:
                self.model = CustomUser
                self.object = CustomUser.objects.get(id = kwargs.get('pk'))
            context = self.get_context_data()
            if self.writersbio is not None:
                context['writersbio'] = self.writersbio
                print(self.writersbio.id)
            return self.render_to_response(context)
        else:
            return HttpResponseRedirect('login')
        
    def get_success_url(self):
        if self.get_context_object_name(self.object).lower() == 'writer':
            return redirect('writerprofile', kwargs={'pk': self.writersbio.id})
        else:
            return reverse('home')

    def post(self, request, *args , **kwargs):
        if self.request.user.type.lower() == 'writer':
            self.model= Writer
            self.object = Writer.objects.get(id = kwargs.get('pk'))
            self.writersbio = WriterProfile.objects.get(user = self.object)
        else:
            self.model = CustomUser
            self.object = CustomUser.objects.get(id = kwargs.get('pk'))
        print(self.object)
        return super().post(request, *args, **kwargs)

class UpdateWriterProfile(generic.UpdateView):
    model = WriterProfile
    fields = ['image', 'bio' , 'education' , 'nationality']
    template_name = 'users/writerprofile.html'




        
        

        


                
            

    #Fitter out articles based on the writer's ID. 

    

templates/users/template_activate_account.html
{% autoescape off %}
Hi {{ user.username }},

  Please click on the link below to confirm your registration

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

templates/users/usersupdate.html
{% extends 'base.html' %}
{% block extra_head %}
    <style>
        .contents{
            max-width: 900px;
            margin-left: auto;
            margin-right: auto;
            margin-top: 5%;
            box-shadow: 0px 5px 10px 0px rgba(0,0,0,0.2);

        }

        .contents > *{
            margin: 20px;
        }

        p > input{
            width: 100%;
            padding: 5px 0;
        }
        
        form > p{
            margin: 20px 0px;
        }

        p > *{
            margin: 5px 0px;
        }

        button{
            margin-bottom: 10px ;
            margin-left: 45%;
            margin-right: 45%;
            padding: 10px;
            border: 1px solid black;
            background: white;
        }

        h1{
            display: flex;
            padding: 5px;
            justify-content: space-between;
            align-items: center;
    
        }

        h1 a{
            font-size: 20px;
            border: 1px solid black;
            padding: 10px;

        }
    </style>
{% endblock %}
{% block content %}
<div class="contents">
    <h1> Edit
        {% if user.is_writer %}
        <a href="{% url 'writerprofile' writersbio.id %}"> Profile <i class="fa-solid fa-chevron-right"></i></a>
    {% endif %}
    </h1>
    
    <form action="" method="post">{% csrf_token %}
    {{ form.media}}
    {{ form.as_p }}
    <button class="btn btn-info ml- " type="submit"> Update</button>
    </form>

</div>
{% endblock %}  

templates/users/writerprofile.html
{% extends 'base.html' %} 
{% block extra_head %} 
    <style>
        .contents{
            max-width: 800px;
            margin: auto;
            padding: 20px;
            box-shadow: 0px 5px 10px 0px rgba(0,0,0,0.2);
        }
        form > p:first-of-type > :not(:first-child):not(:last-child){
            display: none;
        }

        form > p{
            margin: 10px 0;
            position: relative;
        }

        p > *{
            margin: 10px 0;
        }

        p:first-of-type{
            position: relative
        }

        p:first-of-type > label{
            position: absolute;
            left: 14%;
            top: 45%;
            z-index: 10;
        }

        form > p:nth-of-type(3) > *{
            margin-right: 5px;
        }

        form > p:nth-of-type(2) > label{
            display: block;
        }

        form > p:nth-of-type(2) > textarea{
            margin-left: 30px;
        }

        p > input{
            width:100%;
        }

        textarea{
            display: block;
            width: 90%;
            object-fit: cover;
            margin: 0;
            
        }

        select{
            width: 100%;
            padding: 10px 5px;
        }


        #id_education{
            padding: 8px;
        }

        button{
            padding: 10px;
            background-color: grey;
            border: 1px solid black;
            border-radius: 5px;
            margin-left: auto;
        }

        button:hover{
            opacity: 0.8;
        }

    </style>
{% endblock %}
{% block content %}
<div class="contents">
    <h1>Edit</h1>
    <p>User Image: </p>
    <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
            {{ form.as_p }}
    <button class="btn btn-info ml- " type="submit">Update</button>
    </form>

    

    <script>
        var label = document.querySelector('label')
        label.innerHTML = "<i class = 'fa-solid fa-camera' ></i>";
        var first_p = document.querySelectorAll('p')[1]
        document.querySelectorAll('p')[1].childNodes[5].nodeValue = '';
        document.querySelectorAll('p')[1].childNodes[2].nodeValue = '';
        var image_display = document.createElement('img');
        image_display.className = 'image_display';
        image_display.src = '{{object.image.url}}';
        first_p.append(image_display);
        image_display.style ="vertical-align: middle; height: 200px; width: 200px; object-fit: cover; border-radius: 50%; border: 1px black solid; margin: 1em 0;"
    

    </script>
</div>
{% endblock %}  

templates/users/writerspage.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} <title> {{ object.first_name}}'s page </title> {% endblock %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static 'writerspages.css' %}"> 
{% endblock %}
{% block content %}

<div class="content">
 
    <section class="writer-section">
        <div class="writer-bio">
            <div class="bio">
                <img src="{{ writerbio.image.url }}" alt="">
                <div class="wordings">
                    <h2 class="bio-name"> {{object.first_name}} {{object.last_name}}</h2>
                    <a class="article-create" href = "{% url 'article_create' %}"> Create Article </a>
                    <p class="education"> Education:  Cornell University, BA in history </p>
                    <p class="bio-paragraph">Jeff Stein is the White House economics reporter for The Washington Post. 
                        Since joining The Washington Post in November 2017, he has covered the Republican tax law; 
                        the government shutdown; and the administration's economic response to the coronavirus, among other topics. 
                        In 2014, he founded the local news nonprofit the Ithaca Voice in Upstate New York. 
                        The Ithaca Voice has a full-time staff of reporters and remains the best publication in the city
                    </p>
                </div>
            </div>

            <div class="socials">
                <a href="www.facebook.com"> <i class="fa-brands fa-facebook-f"></i> </a>
                <a href="www.twitter.com" > <i class="fa-brands fa-twitter"></i></a>
                <a href="www.linkedin.com"> <i class="fa-brands fa-linkedin"></i> </a>
            </div>


        </div>
        <h3> Latest from {{object.first_name}} {{ object.last_name}} </h3>
       <div class="articles">
            <div class="articles-lists">
            {% if articles %}
                {% for item in articles %}
                <div class="article-box">
                    <h2> <a href="{% url 'article_detail' item.id %} "> {{ item.title}} </a></h2>
                    <p> {{ item.summary}} </p>
                    <p> {{ item.author.first_name }} {{ item.author.last_name}} </p>
                </div>
                {% endfor %}

            {% endif %}
            </div>
       </div>
        
    </section>

</div>

{% endblock %}